name: whatsapp_share
description: Simple way to share message, links or files from your flutter app to specific contact in whatsapp
version: 1.1.1

publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.whatsapp_share
        pluginClass: WhatsappShare
      ios:
        pluginClass: WhatsappShare

dev_dependencies:
  flutter_test:
    sdk: flutter
