name: easy_contact_picker
description: A Flutter contact picker.Writted with pure dart, supported both iOS and Android.
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.liuwei.easy_contact_picker
        pluginClass: EasyContactPickerPlugin
      ios:
        pluginClass: EasyContactPickerPlugin
