name: circle
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.5
  intl: ^0.17.0
  http: ^0.13.4
  share: ^2.0.4
  formz: ^0.4.1
  rxdart: ^0.27.3
  equatable: ^2.0.3
  screenshot: ^1.2.3
  photo_view: ^0.13.0
  geolocator: ^7.7.1
  timer_button: ^2.0.0
  flutter_html: ^2.1.5
  flutter_bloc: ^7.3.3
  google_fonts: ^2.1.0
  url_launcher: ^6.0.15
  image_picker: ^0.8.4+4
  path_provider: ^2.0.7
  image_cropper: ^1.4.1
  dropdown_search: ^2.0.1
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.1.1
  flutter_share_me: ^1.2.0
  firebase_storage: ^10.1.0
  google_mobile_ads: ^1.0.0
  loading_animations: ^2.2.0
  permission_handler: ^8.3.0
  firebase_messaging: ^11.1.0
  proste_bezier_curve: ^2.0.2
  country_code_picker: ^2.0.2
  google_maps_flutter: ^2.1.1
  font_awesome_flutter: ^9.2.0
  double_back_to_close: ^2.0.0
  youtube_player_iframe: ^2.2.2

  form_inputs:
    path: packages/form_inputs

  flutter_chat:
    path: packages/flutter_chat

  force_update:
    path: packages/force_update

  geocoder:
    path: packages/flutter_geocoder

  whatsapp_share:
    path: packages/whatsapp_share

  easy_contact_picker:
    path: packages/easy_contact_picker

  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/home/
    - assets/empty/
    - assets/offer/
    - assets/slider/
    - assets/default/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
